apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project
  labels:
    app: cicd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-project
  template:
    metadata:
      labels:
        app: cicd-project
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cicd-project
          image: ghcr.io/sulukarpuz/cicd-project:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-project
spec:
  type: NodePort
  selector:
    app: cicd-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
